version: "3.9"

services:
  db:
    image: "jaiveerdhanju117/recipe-app-postgres:tagname"
    ports:
      - "5433:5432"
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
  server:
    image: "jaiveerdhanju117/recipe-app-server:tagname"
    ports:
      - "8080:8080"

  frontend:
    image: "jaiveerdhanju117/recipe-app-frontend:tagname"
    ports:
      - "3000:3000"
