version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
  server:
    build: .
    ports:
      - "8080:8080"
